CREATE TABLE `activities` (
	`id` integer PRIMARY KEY NOT NULL,
	`title` text NOT NULL,
	`category` text NOT NULL,
	`status` text DEFAULT 'planned' NOT NULL,
	`start_date` text,
	`end_date` text,
	`location` text NOT NULL,
	`short_description` text NOT NULL,
	`full_description` text NOT NULL,
	`objectives` text NOT NULL,
	`beneficiaries` integer DEFAULT 0 NOT NULL,
	`budget` text,
	`impact` text,
	`images` text,
	`videos` text,
	`documents` text,
	`team` text,
	`sponsors` text,
	`tags` text,
	`created_by` integer,
	`featured` integer DEFAULT false,
	`published_at` text,
	`created_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	`updated_at` integer,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
