CREATE TABLE `projects` (
	`id` integer PRIMARY KEY NOT NULL,
	`title` text NOT NULL,
	`slug` text NOT NULL,
	`category` text NOT NULL,
	`status` text DEFAULT 'planned' NOT NULL,
	`start_date` text,
	`end_date` text,
	`location` text NOT NULL,
	`short_description` text NOT NULL,
	`full_description` text NOT NULL,
	`objectives` text NOT NULL,
	`total_budget` text,
	`funds_raised` text,
	`beneficiaries` integer DEFAULT 0 NOT NULL,
	`duration` text,
	`key_achievements` text,
	`challenges` text,
	`lessons` text,
	`partners` text,
	`team` text,
	`images` text,
	`documents` text,
	`impact_metrics` text,
	`tags` text,
	`created_by` integer,
	`featured` integer DEFAULT false,
	`published_at` text,
	`created_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	`updated_at` integer,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX `projects_slug_unique` ON `projects` (`slug`);